openapi: 3.0.1
info:
  title: CT Parser
  description: The Clinical Trial Parser meticulously extracts and analyzes data from clinical trial records sourced from ClinicalTrials.gov. This application identifies and categorizes the conditions and outcomes being studied by each trial. This is derived by examining the title of the trial, a description of the study, a list of conditions (which are supposed to be but may not be the main diseases that are being studied, sometimes the entered data doesn't indicate the exact condition being studied), and primary and secondary outcomes that are being studied. An example input could be "nctid NCT05859269".
  version: "v1"
servers:
  - url: http://localhost:5003
paths:
  /trial/{trialID}:
    get:
      operationId: getTrial
      summary: Get the title of the trial, a description of the study, a list of conditions (which are supposed to be but may not be the main diseases that are being studied, sometimes the entered data doesn't indicate the exact condition being studied), and primary and secondary outcomes that are being studied.
      parameters:
        - in: path
          name: trialID
          schema:
            type: string
          required: true
          description: NCT ID.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getTrialResponse"
components:
  schemas:
    getTrialResponse:
      type: object
      properties:
        todos:
          type: array
          items:
            type: string
          description: An object containing the title of the trial, a description of the trial, a list of conditions (which are supposed to be but may not be the main diseases that are being studied, sometimes the entered data doesn't indicate the exact condition being studied), and primary and secondary outcomes that are being studied.
